### ISSUE TITLE
AppData / Affiliate Code

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/explorer#20]
**Description**

Affiliate code management

**Additional resources**
Reference for creating custom appData https://docs.google.com/document/d/1ryn3v4m7cXTTXfLfQX9xsRNYZ4PfSXhHVxjodkZHGzQ/edit#
Reference for addData encoded format https://docs.google.com/spreadsheets/d/16RzefdfpmEavl182h6iNEe7fRyAcaATCRYR0hMQ_734/edit#gid=209750149

**Feature breakdown**
It includes:
- [x] Display affiliate data on order details page - only the hash https://github.com/cowprotocol/explorer/issues/157
- [x] Expandable optional are to display decoded affiliate data contents - fetched from IPFS https://github.com/cowprotocol/explorer/issues/157

Good to have:
- [x] Page to manage affiliate data
  - [x] Able to decode appData directly similar to https://codepen.io/pacara/pen/BadZgjg (https://github.com/cowprotocol/explorer/issues/160)
  - [x] Able to create custom appData: Different appCode (other than `CowSwap`) https://github.com/cowprotocol/explorer/issues/160

> Original issue https://github.com/gnosis/gp-ui/issues/849 by @alfetopito

**Comment by ramirotw** [comment]
Added in https://github.com/cowprotocol/explorer/pull/168
