### ISSUE TITLE
Batch Viewer v2

### ISSUE THREAD

**Issue by ramirotw** [cowprotocol/explorer#69]
**Description**
Second iteration of the Batch Viewer, containing some fixes and more features.

**Feature breakdown**
- [x] https://github.com/cowprotocol/explorer/issues/45
- [ ] https://github.com/cowprotocol/explorer/issues/57
- [x] https://github.com/cowprotocol/explorer/issues/41
- [x] https://github.com/cowprotocol/explorer/issues/64
- [x] https://github.com/cowprotocol/explorer/issues/70
- [x] https://github.com/cowprotocol/explorer/issues/71
- [x] https://github.com/cowprotocol/explorer/issues/106

**Bug fixes breakdown**
- [x] https://github.com/cowprotocol/explorer/issues/42
- [x] https://github.com/cowprotocol/explorer/issues/44
- [x] https://github.com/cowprotocol/explorer/issues/43
- [x] https://github.com/cowprotocol/explorer/issues/72

**Nice to have**
- [ ] https://github.com/cowprotocol/explorer/issues/61
- [x] https://github.com/cowprotocol/explorer/issues/48
- [ ] https://github.com/cowprotocol/explorer/issues/46

**Comment by elena-zh** [comment]
Hey @ramirotw , should we include these tasks to the epic? 
 - https://github.com/cowprotocol/explorer/issues/61
 - https://github.com/cowprotocol/explorer/issues/48
 - https://github.com/cowprotocol/explorer/issues/46

Thanks

**Comment by ramirotw** [comment]
Sure, I missed them. Thanks Elena!
